apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  containers:
  - name: mysql
    image: mysql/mysql-server:8.0
    envFrom:
      - secretRef:
          name: istory-db-secret
      - configMapRef:
          name: istory-db-config
    ports:
      - containerPort: 3306
        name: mysql      
    # resources:
    #   limits:
    #     memory: "128Mi"
    #     cpu: "500m"
---
apiVersion: v1
kind: Secret
metadata:
  name: istory-db-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YWRtaW4xMjMK
  MYSQL_PASSWORD: YWRtaW4xMjMK
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: istory-db-config
data:
  MYSQL_DATABASE: 'istory'
  MYSQL_USER: 'dangtong'
