apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod5
  labels:
    app: mysql
spec:
  containers:
    - image: mysql:8.0
      name: mysql
      envFrom:
        - secretRef:
            name: istory-db-secret
        - configMapRef:
            name: istory-db-config
      ports:
        - containerPort: 3306
          name: mysql
      volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: config-volume
          mountPath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf
  volumes:
    - name: config-volume
      configMap:
        name: mysql-config
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: mysql-pv-claim